version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

build:
  commands:
    - pdoc --html justpyplot -o _readthedocs/html --only-modules 